### ISSUE TITLE
Create signed version

### ISSUE THREAD

**Issue by kjetillilleby** [tkellogg/Moq.AutoMocker#17]
Hi,
I like to use AutoMocker, but I need a strong named version, 

Regards,
Kjetil.

**Comment by Keboo** [comment]
I would advocate that we do not create a strong named version. You can read more about the Microsoft recommendations [here](https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/Documentation/project-docs/strong-name-signing.md). In addition it is usually not advantageous for open source solutions to strong name their assemblies as it adds nearly zero value and causes a significant number of headaches. 
In addition this package is expected to be included as part of a unit test project. I would be very interested to hear an argument for why a unit test project would ever need a strong name.

In the very rare case that strong naming is needed, I would suggest adding https://github.com/dsplaisted/strongnamer to your project and using that to add strong names where needed.

**Comment by SH2015** [comment]
The suggestions here doesn't work when you have large project and you have no control of their policy,also any manual work from our side will make it hard to update the package on new version . 
@Keboo
